// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repository

import (
	"context"
	"sync"
)

// Ensure, that FolderRepositoryMock does implement FolderRepository.
// If this is not the case, regenerate this file with moq.
var _ FolderRepository = &FolderRepositoryMock{}

// FolderRepositoryMock is a mock implementation of FolderRepository.
//
//	func TestSomethingThatUsesFolderRepository(t *testing.T) {
//
//		// make and configure a mocked FolderRepository
//		mockedFolderRepository := &FolderRepositoryMock{
//			CreateConfigFunc: func(ctx context.Context, path string, c *Config) error {
//				panic("mock out the CreateConfig method")
//			},
//			CreateFolderFunc: func(ctx context.Context, name string) error {
//				panic("mock out the CreateFolder method")
//			},
//			ExistsFunc: func(ctx context.Context, name string) (bool, error) {
//				panic("mock out the Exists method")
//			},
//			GetConfigFunc: func(ctx context.Context, path string) (*Config, error) {
//				panic("mock out the GetConfig method")
//			},
//		}
//
//		// use mockedFolderRepository in code that requires FolderRepository
//		// and then make assertions.
//
//	}
type FolderRepositoryMock struct {
	// CreateConfigFunc mocks the CreateConfig method.
	CreateConfigFunc func(ctx context.Context, path string, c *Config) error

	// CreateFolderFunc mocks the CreateFolder method.
	CreateFolderFunc func(ctx context.Context, name string) error

	// ExistsFunc mocks the Exists method.
	ExistsFunc func(ctx context.Context, name string) (bool, error)

	// GetConfigFunc mocks the GetConfig method.
	GetConfigFunc func(ctx context.Context, path string) (*Config, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateConfig holds details about calls to the CreateConfig method.
		CreateConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// C is the c argument value.
			C *Config
		}
		// CreateFolder holds details about calls to the CreateFolder method.
		CreateFolder []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetConfig holds details about calls to the GetConfig method.
		GetConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockCreateConfig sync.RWMutex
	lockCreateFolder sync.RWMutex
	lockExists       sync.RWMutex
	lockGetConfig    sync.RWMutex
}

// CreateConfig calls CreateConfigFunc.
func (mock *FolderRepositoryMock) CreateConfig(ctx context.Context, path string, c *Config) error {
	if mock.CreateConfigFunc == nil {
		panic("FolderRepositoryMock.CreateConfigFunc: method is nil but FolderRepository.CreateConfig was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
		C    *Config
	}{
		Ctx:  ctx,
		Path: path,
		C:    c,
	}
	mock.lockCreateConfig.Lock()
	mock.calls.CreateConfig = append(mock.calls.CreateConfig, callInfo)
	mock.lockCreateConfig.Unlock()
	return mock.CreateConfigFunc(ctx, path, c)
}

// CreateConfigCalls gets all the calls that were made to CreateConfig.
// Check the length with:
//
//	len(mockedFolderRepository.CreateConfigCalls())
func (mock *FolderRepositoryMock) CreateConfigCalls() []struct {
	Ctx  context.Context
	Path string
	C    *Config
} {
	var calls []struct {
		Ctx  context.Context
		Path string
		C    *Config
	}
	mock.lockCreateConfig.RLock()
	calls = mock.calls.CreateConfig
	mock.lockCreateConfig.RUnlock()
	return calls
}

// CreateFolder calls CreateFolderFunc.
func (mock *FolderRepositoryMock) CreateFolder(ctx context.Context, name string) error {
	if mock.CreateFolderFunc == nil {
		panic("FolderRepositoryMock.CreateFolderFunc: method is nil but FolderRepository.CreateFolder was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockCreateFolder.Lock()
	mock.calls.CreateFolder = append(mock.calls.CreateFolder, callInfo)
	mock.lockCreateFolder.Unlock()
	return mock.CreateFolderFunc(ctx, name)
}

// CreateFolderCalls gets all the calls that were made to CreateFolder.
// Check the length with:
//
//	len(mockedFolderRepository.CreateFolderCalls())
func (mock *FolderRepositoryMock) CreateFolderCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockCreateFolder.RLock()
	calls = mock.calls.CreateFolder
	mock.lockCreateFolder.RUnlock()
	return calls
}

// Exists calls ExistsFunc.
func (mock *FolderRepositoryMock) Exists(ctx context.Context, name string) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("FolderRepositoryMock.ExistsFunc: method is nil but FolderRepository.Exists was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(ctx, name)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedFolderRepository.ExistsCalls())
func (mock *FolderRepositoryMock) ExistsCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}

// GetConfig calls GetConfigFunc.
func (mock *FolderRepositoryMock) GetConfig(ctx context.Context, path string) (*Config, error) {
	if mock.GetConfigFunc == nil {
		panic("FolderRepositoryMock.GetConfigFunc: method is nil but FolderRepository.GetConfig was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockGetConfig.Lock()
	mock.calls.GetConfig = append(mock.calls.GetConfig, callInfo)
	mock.lockGetConfig.Unlock()
	return mock.GetConfigFunc(ctx, path)
}

// GetConfigCalls gets all the calls that were made to GetConfig.
// Check the length with:
//
//	len(mockedFolderRepository.GetConfigCalls())
func (mock *FolderRepositoryMock) GetConfigCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockGetConfig.RLock()
	calls = mock.calls.GetConfig
	mock.lockGetConfig.RUnlock()
	return calls
}
