version: 2

project_name: stowmark

builds:
  - id: stowmark_cli
    main: ./cmd/cli
    binary: stowmark

    env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - amd64
      - arm64

  - id: stowmark_cli_windows
    main: ./cmd/cli
    binary: stowmark

    env:
      - CGO_ENABLED=0

    goos:
      - windows

    goarch:
      - amd64
      - arm64

archives:
  - id: stowmark_archives
    ids:
      - stowmark_cli
      - stowmark_cli_windows

    format_overrides:
      - goos: windows
        formats:
          - zip

nfpms:
  - id: stowmark_deb
    package_name: stowmark

    ids:
      - stowmark_cli

    vendor: bruli-lab
    homepage: https://stowmark.dev
    maintainer: Pablo Braulio <brulics@gmail.com>
    description: Immutable snapshot backup tool
    license: Apache-2.0

    formats:
      - deb

    bindir: /usr/bin
    section: utils
    priority: optional

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

changelog:
  disable: true

release:
  mode: keep-existing
