version: '3'

vars:
  GOLANGCI_LINT_VERSION: 'v2.13.1'

includes:
    ssh:
        taskfile: ./taskfiles/ssh/Taskfile.yaml
        dir: .
    smb:
        taskfile: ./taskfiles/smb/Taskfile.yaml
        dir: .
    s3:
        taskfile: ./taskfiles/s3/Taskfile.yaml
        dir: .

    webdav:
        taskfile: ./taskfiles/webdav/Taskfile.yaml
        dir: .

    gcs:
        taskfile: ./taskfiles/gcs/Taskfile.yaml
        dir: .


silent: false

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  fmt:
    desc: Formating Go with gofumpt
    cmds:
      - |
        set -euo pipefail
        echo "👉 Formatting code with gofumpt..."
        go tool gofumpt -w .

  fix:
    desc: fixing code
    cmds:
      - |
        set -euo pipefail
        echo "👉 Running go fix..."
        go fix -v ./...

  security:
    desc: Check vulnerabilities
    cmds:
      - |
        set -euo pipefail
        echo "👉 Check security"
        go tool govulncheck ./...

  install-lint:
    desc: Instal·lar golangci-lint
    cmds:
      - |
        set -euo pipefail
        echo "🔧 Installing golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
        go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}

  lint:
    desc: Executing golangci-lint
    deps:
      - install-lint
    cmds:
      - |
        set -euo pipefail
        echo "🚀 Executing golangci-lint..."
        golangci-lint run ./...

  unit-test:
    desc: Executing unit tests amb race, coverage i tparse
    cmds:
      - |
        set -euo pipefail
        echo "🧪 Running unit tests (race, JSON → tparse)..."
        go test -race ./... -json -cover -coverprofile=coverage.out | go tool tparse -all

  integration-test:
    desc: Run integration tests
    cmds:
      - |
        set -euo pipefail
        echo "🧪 Running integration tests..."
        go tool gotestsum \
          --format testname \
          -- \
          -tags=integration \
          -count=1 \
          ./pkg/stowmark

  check:
    desc: Executing fmt, security, lint i test
    deps:
      - fmt
      - fix
      - security
      - lint
      - unit-test