// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package encryption

import (
	"context"
	"crypto/rsa"
	"sync"
)

// Ensure, that AsymmetricKeyPairRepositoryMock does implement AsymmetricKeyPairRepository.
// If this is not the case, regenerate this file with moq.
var _ AsymmetricKeyPairRepository = &AsymmetricKeyPairRepositoryMock{}

// AsymmetricKeyPairRepositoryMock is a mock implementation of AsymmetricKeyPairRepository.
//
//	func TestSomethingThatUsesAsymmetricKeyPairRepository(t *testing.T) {
//
//		// make and configure a mocked AsymmetricKeyPairRepository
//		mockedAsymmetricKeyPairRepository := &AsymmetricKeyPairRepositoryMock{
//			CreatePrivateKeyFunc: func(ctx context.Context, filePath string, privateKey *rsa.PrivateKey) error {
//				panic("mock out the CreatePrivateKey method")
//			},
//			CreatePublicKeyFunc: func(ctx context.Context, filePath string, publicKey *rsa.PublicKey) error {
//				panic("mock out the CreatePublicKey method")
//			},
//			PublicKeyFingerPrintFunc: func(ctx context.Context, publicKey *rsa.PublicKey) (string, error) {
//				panic("mock out the PublicKeyFingerPrint method")
//			},
//			ReadRSAPrivateKeyFunc: func(ctx context.Context, filePath string) (*rsa.PrivateKey, error) {
//				panic("mock out the ReadRSAPrivateKey method")
//			},
//			ReadRSAPublicKeyFunc: func(ctx context.Context, filePath string) (*rsa.PublicKey, error) {
//				panic("mock out the ReadRSAPublicKey method")
//			},
//		}
//
//		// use mockedAsymmetricKeyPairRepository in code that requires AsymmetricKeyPairRepository
//		// and then make assertions.
//
//	}
type AsymmetricKeyPairRepositoryMock struct {
	// CreatePrivateKeyFunc mocks the CreatePrivateKey method.
	CreatePrivateKeyFunc func(ctx context.Context, filePath string, privateKey *rsa.PrivateKey) error

	// CreatePublicKeyFunc mocks the CreatePublicKey method.
	CreatePublicKeyFunc func(ctx context.Context, filePath string, publicKey *rsa.PublicKey) error

	// PublicKeyFingerPrintFunc mocks the PublicKeyFingerPrint method.
	PublicKeyFingerPrintFunc func(ctx context.Context, publicKey *rsa.PublicKey) (string, error)

	// ReadRSAPrivateKeyFunc mocks the ReadRSAPrivateKey method.
	ReadRSAPrivateKeyFunc func(ctx context.Context, filePath string) (*rsa.PrivateKey, error)

	// ReadRSAPublicKeyFunc mocks the ReadRSAPublicKey method.
	ReadRSAPublicKeyFunc func(ctx context.Context, filePath string) (*rsa.PublicKey, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreatePrivateKey holds details about calls to the CreatePrivateKey method.
		CreatePrivateKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// PrivateKey is the privateKey argument value.
			PrivateKey *rsa.PrivateKey
		}
		// CreatePublicKey holds details about calls to the CreatePublicKey method.
		CreatePublicKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// PublicKey is the publicKey argument value.
			PublicKey *rsa.PublicKey
		}
		// PublicKeyFingerPrint holds details about calls to the PublicKeyFingerPrint method.
		PublicKeyFingerPrint []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PublicKey is the publicKey argument value.
			PublicKey *rsa.PublicKey
		}
		// ReadRSAPrivateKey holds details about calls to the ReadRSAPrivateKey method.
		ReadRSAPrivateKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
		}
		// ReadRSAPublicKey holds details about calls to the ReadRSAPublicKey method.
		ReadRSAPublicKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
		}
	}
	lockCreatePrivateKey     sync.RWMutex
	lockCreatePublicKey      sync.RWMutex
	lockPublicKeyFingerPrint sync.RWMutex
	lockReadRSAPrivateKey    sync.RWMutex
	lockReadRSAPublicKey     sync.RWMutex
}

// CreatePrivateKey calls CreatePrivateKeyFunc.
func (mock *AsymmetricKeyPairRepositoryMock) CreatePrivateKey(ctx context.Context, filePath string, privateKey *rsa.PrivateKey) error {
	if mock.CreatePrivateKeyFunc == nil {
		panic("AsymmetricKeyPairRepositoryMock.CreatePrivateKeyFunc: method is nil but AsymmetricKeyPairRepository.CreatePrivateKey was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		FilePath   string
		PrivateKey *rsa.PrivateKey
	}{
		Ctx:        ctx,
		FilePath:   filePath,
		PrivateKey: privateKey,
	}
	mock.lockCreatePrivateKey.Lock()
	mock.calls.CreatePrivateKey = append(mock.calls.CreatePrivateKey, callInfo)
	mock.lockCreatePrivateKey.Unlock()
	return mock.CreatePrivateKeyFunc(ctx, filePath, privateKey)
}

// CreatePrivateKeyCalls gets all the calls that were made to CreatePrivateKey.
// Check the length with:
//
//	len(mockedAsymmetricKeyPairRepository.CreatePrivateKeyCalls())
func (mock *AsymmetricKeyPairRepositoryMock) CreatePrivateKeyCalls() []struct {
	Ctx        context.Context
	FilePath   string
	PrivateKey *rsa.PrivateKey
} {
	var calls []struct {
		Ctx        context.Context
		FilePath   string
		PrivateKey *rsa.PrivateKey
	}
	mock.lockCreatePrivateKey.RLock()
	calls = mock.calls.CreatePrivateKey
	mock.lockCreatePrivateKey.RUnlock()
	return calls
}

// CreatePublicKey calls CreatePublicKeyFunc.
func (mock *AsymmetricKeyPairRepositoryMock) CreatePublicKey(ctx context.Context, filePath string, publicKey *rsa.PublicKey) error {
	if mock.CreatePublicKeyFunc == nil {
		panic("AsymmetricKeyPairRepositoryMock.CreatePublicKeyFunc: method is nil but AsymmetricKeyPairRepository.CreatePublicKey was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		FilePath  string
		PublicKey *rsa.PublicKey
	}{
		Ctx:       ctx,
		FilePath:  filePath,
		PublicKey: publicKey,
	}
	mock.lockCreatePublicKey.Lock()
	mock.calls.CreatePublicKey = append(mock.calls.CreatePublicKey, callInfo)
	mock.lockCreatePublicKey.Unlock()
	return mock.CreatePublicKeyFunc(ctx, filePath, publicKey)
}

// CreatePublicKeyCalls gets all the calls that were made to CreatePublicKey.
// Check the length with:
//
//	len(mockedAsymmetricKeyPairRepository.CreatePublicKeyCalls())
func (mock *AsymmetricKeyPairRepositoryMock) CreatePublicKeyCalls() []struct {
	Ctx       context.Context
	FilePath  string
	PublicKey *rsa.PublicKey
} {
	var calls []struct {
		Ctx       context.Context
		FilePath  string
		PublicKey *rsa.PublicKey
	}
	mock.lockCreatePublicKey.RLock()
	calls = mock.calls.CreatePublicKey
	mock.lockCreatePublicKey.RUnlock()
	return calls
}

// PublicKeyFingerPrint calls PublicKeyFingerPrintFunc.
func (mock *AsymmetricKeyPairRepositoryMock) PublicKeyFingerPrint(ctx context.Context, publicKey *rsa.PublicKey) (string, error) {
	if mock.PublicKeyFingerPrintFunc == nil {
		panic("AsymmetricKeyPairRepositoryMock.PublicKeyFingerPrintFunc: method is nil but AsymmetricKeyPairRepository.PublicKeyFingerPrint was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		PublicKey *rsa.PublicKey
	}{
		Ctx:       ctx,
		PublicKey: publicKey,
	}
	mock.lockPublicKeyFingerPrint.Lock()
	mock.calls.PublicKeyFingerPrint = append(mock.calls.PublicKeyFingerPrint, callInfo)
	mock.lockPublicKeyFingerPrint.Unlock()
	return mock.PublicKeyFingerPrintFunc(ctx, publicKey)
}

// PublicKeyFingerPrintCalls gets all the calls that were made to PublicKeyFingerPrint.
// Check the length with:
//
//	len(mockedAsymmetricKeyPairRepository.PublicKeyFingerPrintCalls())
func (mock *AsymmetricKeyPairRepositoryMock) PublicKeyFingerPrintCalls() []struct {
	Ctx       context.Context
	PublicKey *rsa.PublicKey
} {
	var calls []struct {
		Ctx       context.Context
		PublicKey *rsa.PublicKey
	}
	mock.lockPublicKeyFingerPrint.RLock()
	calls = mock.calls.PublicKeyFingerPrint
	mock.lockPublicKeyFingerPrint.RUnlock()
	return calls
}

// ReadRSAPrivateKey calls ReadRSAPrivateKeyFunc.
func (mock *AsymmetricKeyPairRepositoryMock) ReadRSAPrivateKey(ctx context.Context, filePath string) (*rsa.PrivateKey, error) {
	if mock.ReadRSAPrivateKeyFunc == nil {
		panic("AsymmetricKeyPairRepositoryMock.ReadRSAPrivateKeyFunc: method is nil but AsymmetricKeyPairRepository.ReadRSAPrivateKey was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
	}{
		Ctx:      ctx,
		FilePath: filePath,
	}
	mock.lockReadRSAPrivateKey.Lock()
	mock.calls.ReadRSAPrivateKey = append(mock.calls.ReadRSAPrivateKey, callInfo)
	mock.lockReadRSAPrivateKey.Unlock()
	return mock.ReadRSAPrivateKeyFunc(ctx, filePath)
}

// ReadRSAPrivateKeyCalls gets all the calls that were made to ReadRSAPrivateKey.
// Check the length with:
//
//	len(mockedAsymmetricKeyPairRepository.ReadRSAPrivateKeyCalls())
func (mock *AsymmetricKeyPairRepositoryMock) ReadRSAPrivateKeyCalls() []struct {
	Ctx      context.Context
	FilePath string
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
	}
	mock.lockReadRSAPrivateKey.RLock()
	calls = mock.calls.ReadRSAPrivateKey
	mock.lockReadRSAPrivateKey.RUnlock()
	return calls
}

// ReadRSAPublicKey calls ReadRSAPublicKeyFunc.
func (mock *AsymmetricKeyPairRepositoryMock) ReadRSAPublicKey(ctx context.Context, filePath string) (*rsa.PublicKey, error) {
	if mock.ReadRSAPublicKeyFunc == nil {
		panic("AsymmetricKeyPairRepositoryMock.ReadRSAPublicKeyFunc: method is nil but AsymmetricKeyPairRepository.ReadRSAPublicKey was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
	}{
		Ctx:      ctx,
		FilePath: filePath,
	}
	mock.lockReadRSAPublicKey.Lock()
	mock.calls.ReadRSAPublicKey = append(mock.calls.ReadRSAPublicKey, callInfo)
	mock.lockReadRSAPublicKey.Unlock()
	return mock.ReadRSAPublicKeyFunc(ctx, filePath)
}

// ReadRSAPublicKeyCalls gets all the calls that were made to ReadRSAPublicKey.
// Check the length with:
//
//	len(mockedAsymmetricKeyPairRepository.ReadRSAPublicKeyCalls())
func (mock *AsymmetricKeyPairRepositoryMock) ReadRSAPublicKeyCalls() []struct {
	Ctx      context.Context
	FilePath string
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
	}
	mock.lockReadRSAPublicKey.RLock()
	calls = mock.calls.ReadRSAPublicKey
	mock.lockReadRSAPublicKey.RUnlock()
	return calls
}

// Ensure, that SymmetricKeyRepositoryMock does implement SymmetricKeyRepository.
// If this is not the case, regenerate this file with moq.
var _ SymmetricKeyRepository = &SymmetricKeyRepositoryMock{}

// SymmetricKeyRepositoryMock is a mock implementation of SymmetricKeyRepository.
//
//	func TestSomethingThatUsesSymmetricKeyRepository(t *testing.T) {
//
//		// make and configure a mocked SymmetricKeyRepository
//		mockedSymmetricKeyRepository := &SymmetricKeyRepositoryMock{
//			DecodeAndDecryptSymmetricKeyFunc: func(ctx context.Context, privateKey *rsa.PrivateKey, encodedKey string) ([]byte, error) {
//				panic("mock out the DecodeAndDecryptSymmetricKey method")
//			},
//			EncryptSymmetricKeyFunc: func(ctx context.Context, publicKey *rsa.PublicKey, symmetricKey []byte) ([]byte, error) {
//				panic("mock out the EncryptSymmetricKey method")
//			},
//			GenerateSymmetricKeyFunc: func(ctx context.Context) ([]byte, error) {
//				panic("mock out the GenerateSymmetricKey method")
//			},
//		}
//
//		// use mockedSymmetricKeyRepository in code that requires SymmetricKeyRepository
//		// and then make assertions.
//
//	}
type SymmetricKeyRepositoryMock struct {
	// DecodeAndDecryptSymmetricKeyFunc mocks the DecodeAndDecryptSymmetricKey method.
	DecodeAndDecryptSymmetricKeyFunc func(ctx context.Context, privateKey *rsa.PrivateKey, encodedKey string) ([]byte, error)

	// EncryptSymmetricKeyFunc mocks the EncryptSymmetricKey method.
	EncryptSymmetricKeyFunc func(ctx context.Context, publicKey *rsa.PublicKey, symmetricKey []byte) ([]byte, error)

	// GenerateSymmetricKeyFunc mocks the GenerateSymmetricKey method.
	GenerateSymmetricKeyFunc func(ctx context.Context) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// DecodeAndDecryptSymmetricKey holds details about calls to the DecodeAndDecryptSymmetricKey method.
		DecodeAndDecryptSymmetricKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PrivateKey is the privateKey argument value.
			PrivateKey *rsa.PrivateKey
			// EncodedKey is the encodedKey argument value.
			EncodedKey string
		}
		// EncryptSymmetricKey holds details about calls to the EncryptSymmetricKey method.
		EncryptSymmetricKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PublicKey is the publicKey argument value.
			PublicKey *rsa.PublicKey
			// SymmetricKey is the symmetricKey argument value.
			SymmetricKey []byte
		}
		// GenerateSymmetricKey holds details about calls to the GenerateSymmetricKey method.
		GenerateSymmetricKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockDecodeAndDecryptSymmetricKey sync.RWMutex
	lockEncryptSymmetricKey          sync.RWMutex
	lockGenerateSymmetricKey         sync.RWMutex
}

// DecodeAndDecryptSymmetricKey calls DecodeAndDecryptSymmetricKeyFunc.
func (mock *SymmetricKeyRepositoryMock) DecodeAndDecryptSymmetricKey(ctx context.Context, privateKey *rsa.PrivateKey, encodedKey string) ([]byte, error) {
	if mock.DecodeAndDecryptSymmetricKeyFunc == nil {
		panic("SymmetricKeyRepositoryMock.DecodeAndDecryptSymmetricKeyFunc: method is nil but SymmetricKeyRepository.DecodeAndDecryptSymmetricKey was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		PrivateKey *rsa.PrivateKey
		EncodedKey string
	}{
		Ctx:        ctx,
		PrivateKey: privateKey,
		EncodedKey: encodedKey,
	}
	mock.lockDecodeAndDecryptSymmetricKey.Lock()
	mock.calls.DecodeAndDecryptSymmetricKey = append(mock.calls.DecodeAndDecryptSymmetricKey, callInfo)
	mock.lockDecodeAndDecryptSymmetricKey.Unlock()
	return mock.DecodeAndDecryptSymmetricKeyFunc(ctx, privateKey, encodedKey)
}

// DecodeAndDecryptSymmetricKeyCalls gets all the calls that were made to DecodeAndDecryptSymmetricKey.
// Check the length with:
//
//	len(mockedSymmetricKeyRepository.DecodeAndDecryptSymmetricKeyCalls())
func (mock *SymmetricKeyRepositoryMock) DecodeAndDecryptSymmetricKeyCalls() []struct {
	Ctx        context.Context
	PrivateKey *rsa.PrivateKey
	EncodedKey string
} {
	var calls []struct {
		Ctx        context.Context
		PrivateKey *rsa.PrivateKey
		EncodedKey string
	}
	mock.lockDecodeAndDecryptSymmetricKey.RLock()
	calls = mock.calls.DecodeAndDecryptSymmetricKey
	mock.lockDecodeAndDecryptSymmetricKey.RUnlock()
	return calls
}

// EncryptSymmetricKey calls EncryptSymmetricKeyFunc.
func (mock *SymmetricKeyRepositoryMock) EncryptSymmetricKey(ctx context.Context, publicKey *rsa.PublicKey, symmetricKey []byte) ([]byte, error) {
	if mock.EncryptSymmetricKeyFunc == nil {
		panic("SymmetricKeyRepositoryMock.EncryptSymmetricKeyFunc: method is nil but SymmetricKeyRepository.EncryptSymmetricKey was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		PublicKey    *rsa.PublicKey
		SymmetricKey []byte
	}{
		Ctx:          ctx,
		PublicKey:    publicKey,
		SymmetricKey: symmetricKey,
	}
	mock.lockEncryptSymmetricKey.Lock()
	mock.calls.EncryptSymmetricKey = append(mock.calls.EncryptSymmetricKey, callInfo)
	mock.lockEncryptSymmetricKey.Unlock()
	return mock.EncryptSymmetricKeyFunc(ctx, publicKey, symmetricKey)
}

// EncryptSymmetricKeyCalls gets all the calls that were made to EncryptSymmetricKey.
// Check the length with:
//
//	len(mockedSymmetricKeyRepository.EncryptSymmetricKeyCalls())
func (mock *SymmetricKeyRepositoryMock) EncryptSymmetricKeyCalls() []struct {
	Ctx          context.Context
	PublicKey    *rsa.PublicKey
	SymmetricKey []byte
} {
	var calls []struct {
		Ctx          context.Context
		PublicKey    *rsa.PublicKey
		SymmetricKey []byte
	}
	mock.lockEncryptSymmetricKey.RLock()
	calls = mock.calls.EncryptSymmetricKey
	mock.lockEncryptSymmetricKey.RUnlock()
	return calls
}

// GenerateSymmetricKey calls GenerateSymmetricKeyFunc.
func (mock *SymmetricKeyRepositoryMock) GenerateSymmetricKey(ctx context.Context) ([]byte, error) {
	if mock.GenerateSymmetricKeyFunc == nil {
		panic("SymmetricKeyRepositoryMock.GenerateSymmetricKeyFunc: method is nil but SymmetricKeyRepository.GenerateSymmetricKey was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGenerateSymmetricKey.Lock()
	mock.calls.GenerateSymmetricKey = append(mock.calls.GenerateSymmetricKey, callInfo)
	mock.lockGenerateSymmetricKey.Unlock()
	return mock.GenerateSymmetricKeyFunc(ctx)
}

// GenerateSymmetricKeyCalls gets all the calls that were made to GenerateSymmetricKey.
// Check the length with:
//
//	len(mockedSymmetricKeyRepository.GenerateSymmetricKeyCalls())
func (mock *SymmetricKeyRepositoryMock) GenerateSymmetricKeyCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGenerateSymmetricKey.RLock()
	calls = mock.calls.GenerateSymmetricKey
	mock.lockGenerateSymmetricKey.RUnlock()
	return calls
}
