// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package snapshot

import (
	"context"
	"sync"
)

// Ensure, that SourceRepositoryMock does implement SourceRepository.
// If this is not the case, regenerate this file with moq.
var _ SourceRepository = &SourceRepositoryMock{}

// SourceRepositoryMock is a mock implementation of SourceRepository.
//
//	func TestSomethingThatUsesSourceRepository(t *testing.T) {
//
//		// make and configure a mocked SourceRepository
//		mockedSourceRepository := &SourceRepositoryMock{
//			CalculateHashFunc: func(ctx context.Context, filePath string) (string, error) {
//				panic("mock out the CalculateHash method")
//			},
//			ExploreFunc: func(ctx context.Context, sourcePath string) (*Source, error) {
//				panic("mock out the Explore method")
//			},
//		}
//
//		// use mockedSourceRepository in code that requires SourceRepository
//		// and then make assertions.
//
//	}
type SourceRepositoryMock struct {
	// CalculateHashFunc mocks the CalculateHash method.
	CalculateHashFunc func(ctx context.Context, filePath string) (string, error)

	// ExploreFunc mocks the Explore method.
	ExploreFunc func(ctx context.Context, sourcePath string) (*Source, error)

	// calls tracks calls to the methods.
	calls struct {
		// CalculateHash holds details about calls to the CalculateHash method.
		CalculateHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
		}
		// Explore holds details about calls to the Explore method.
		Explore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SourcePath is the sourcePath argument value.
			SourcePath string
		}
	}
	lockCalculateHash sync.RWMutex
	lockExplore       sync.RWMutex
}

// CalculateHash calls CalculateHashFunc.
func (mock *SourceRepositoryMock) CalculateHash(ctx context.Context, filePath string) (string, error) {
	if mock.CalculateHashFunc == nil {
		panic("SourceRepositoryMock.CalculateHashFunc: method is nil but SourceRepository.CalculateHash was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
	}{
		Ctx:      ctx,
		FilePath: filePath,
	}
	mock.lockCalculateHash.Lock()
	mock.calls.CalculateHash = append(mock.calls.CalculateHash, callInfo)
	mock.lockCalculateHash.Unlock()
	return mock.CalculateHashFunc(ctx, filePath)
}

// CalculateHashCalls gets all the calls that were made to CalculateHash.
// Check the length with:
//
//	len(mockedSourceRepository.CalculateHashCalls())
func (mock *SourceRepositoryMock) CalculateHashCalls() []struct {
	Ctx      context.Context
	FilePath string
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
	}
	mock.lockCalculateHash.RLock()
	calls = mock.calls.CalculateHash
	mock.lockCalculateHash.RUnlock()
	return calls
}

// Explore calls ExploreFunc.
func (mock *SourceRepositoryMock) Explore(ctx context.Context, sourcePath string) (*Source, error) {
	if mock.ExploreFunc == nil {
		panic("SourceRepositoryMock.ExploreFunc: method is nil but SourceRepository.Explore was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		SourcePath string
	}{
		Ctx:        ctx,
		SourcePath: sourcePath,
	}
	mock.lockExplore.Lock()
	mock.calls.Explore = append(mock.calls.Explore, callInfo)
	mock.lockExplore.Unlock()
	return mock.ExploreFunc(ctx, sourcePath)
}

// ExploreCalls gets all the calls that were made to Explore.
// Check the length with:
//
//	len(mockedSourceRepository.ExploreCalls())
func (mock *SourceRepositoryMock) ExploreCalls() []struct {
	Ctx        context.Context
	SourcePath string
} {
	var calls []struct {
		Ctx        context.Context
		SourcePath string
	}
	mock.lockExplore.RLock()
	calls = mock.calls.Explore
	mock.lockExplore.RUnlock()
	return calls
}

// Ensure, that ManifestRepositoryMock does implement ManifestRepository.
// If this is not the case, regenerate this file with moq.
var _ ManifestRepository = &ManifestRepositoryMock{}

// ManifestRepositoryMock is a mock implementation of ManifestRepository.
//
//	func TestSomethingThatUsesManifestRepository(t *testing.T) {
//
//		// make and configure a mocked ManifestRepository
//		mockedManifestRepository := &ManifestRepositoryMock{
//			ListFunc: func(ctx context.Context) ([]Manifest, error) {
//				panic("mock out the List method")
//			},
//			SaveFunc: func(ctx context.Context, m *Manifest) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedManifestRepository in code that requires ManifestRepository
//		// and then make assertions.
//
//	}
type ManifestRepositoryMock struct {
	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]Manifest, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, m *Manifest) error

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M *Manifest
		}
	}
	lockList sync.RWMutex
	lockSave sync.RWMutex
}

// List calls ListFunc.
func (mock *ManifestRepositoryMock) List(ctx context.Context) ([]Manifest, error) {
	if mock.ListFunc == nil {
		panic("ManifestRepositoryMock.ListFunc: method is nil but ManifestRepository.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManifestRepository.ListCalls())
func (mock *ManifestRepositoryMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *ManifestRepositoryMock) Save(ctx context.Context, m *Manifest) error {
	if mock.SaveFunc == nil {
		panic("ManifestRepositoryMock.SaveFunc: method is nil but ManifestRepository.Save was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   *Manifest
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, m)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedManifestRepository.SaveCalls())
func (mock *ManifestRepositoryMock) SaveCalls() []struct {
	Ctx context.Context
	M   *Manifest
} {
	var calls []struct {
		Ctx context.Context
		M   *Manifest
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that ObjectRepositoryMock does implement ObjectRepository.
// If this is not the case, regenerate this file with moq.
var _ ObjectRepository = &ObjectRepositoryMock{}

// ObjectRepositoryMock is a mock implementation of ObjectRepository.
//
//	func TestSomethingThatUsesObjectRepository(t *testing.T) {
//
//		// make and configure a mocked ObjectRepository
//		mockedObjectRepository := &ObjectRepositoryMock{
//			AlreadyExistsFunc: func(ctx context.Context, obj *File) (bool, error) {
//				panic("mock out the AlreadyExists method")
//			},
//			SaveFunc: func(ctx context.Context, obj *File) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedObjectRepository in code that requires ObjectRepository
//		// and then make assertions.
//
//	}
type ObjectRepositoryMock struct {
	// AlreadyExistsFunc mocks the AlreadyExists method.
	AlreadyExistsFunc func(ctx context.Context, obj *File) (bool, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, obj *File) error

	// calls tracks calls to the methods.
	calls struct {
		// AlreadyExists holds details about calls to the AlreadyExists method.
		AlreadyExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Obj is the obj argument value.
			Obj *File
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Obj is the obj argument value.
			Obj *File
		}
	}
	lockAlreadyExists sync.RWMutex
	lockSave          sync.RWMutex
}

// AlreadyExists calls AlreadyExistsFunc.
func (mock *ObjectRepositoryMock) AlreadyExists(ctx context.Context, obj *File) (bool, error) {
	if mock.AlreadyExistsFunc == nil {
		panic("ObjectRepositoryMock.AlreadyExistsFunc: method is nil but ObjectRepository.AlreadyExists was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Obj *File
	}{
		Ctx: ctx,
		Obj: obj,
	}
	mock.lockAlreadyExists.Lock()
	mock.calls.AlreadyExists = append(mock.calls.AlreadyExists, callInfo)
	mock.lockAlreadyExists.Unlock()
	return mock.AlreadyExistsFunc(ctx, obj)
}

// AlreadyExistsCalls gets all the calls that were made to AlreadyExists.
// Check the length with:
//
//	len(mockedObjectRepository.AlreadyExistsCalls())
func (mock *ObjectRepositoryMock) AlreadyExistsCalls() []struct {
	Ctx context.Context
	Obj *File
} {
	var calls []struct {
		Ctx context.Context
		Obj *File
	}
	mock.lockAlreadyExists.RLock()
	calls = mock.calls.AlreadyExists
	mock.lockAlreadyExists.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *ObjectRepositoryMock) Save(ctx context.Context, obj *File) error {
	if mock.SaveFunc == nil {
		panic("ObjectRepositoryMock.SaveFunc: method is nil but ObjectRepository.Save was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Obj *File
	}{
		Ctx: ctx,
		Obj: obj,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, obj)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedObjectRepository.SaveCalls())
func (mock *ObjectRepositoryMock) SaveCalls() []struct {
	Ctx context.Context
	Obj *File
} {
	var calls []struct {
		Ctx context.Context
		Obj *File
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
