// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package snapshot

import (
	"context"
	"github.com/bruli-lab/stowmark/internal/domain/repository"
	"io"
	"sync"
)

// Ensure, that SourceRepositoryMock does implement SourceRepository.
// If this is not the case, regenerate this file with moq.
var _ SourceRepository = &SourceRepositoryMock{}

// SourceRepositoryMock is a mock implementation of SourceRepository.
//
//	func TestSomethingThatUsesSourceRepository(t *testing.T) {
//
//		// make and configure a mocked SourceRepository
//		mockedSourceRepository := &SourceRepositoryMock{
//			CalculateChunksFunc: func(ctx context.Context, filePath string, size int64, comp *repository.Compression) ([]Chunk, error) {
//				panic("mock out the CalculateChunks method")
//			},
//			CalculateHashFunc: func(ctx context.Context, filePath string, comp *repository.Compression) (string, error) {
//				panic("mock out the CalculateHash method")
//			},
//			ExploreFunc: func(ctx context.Context, sourcePath string) (*Source, error) {
//				panic("mock out the Explore method")
//			},
//		}
//
//		// use mockedSourceRepository in code that requires SourceRepository
//		// and then make assertions.
//
//	}
type SourceRepositoryMock struct {
	// CalculateChunksFunc mocks the CalculateChunks method.
	CalculateChunksFunc func(ctx context.Context, filePath string, size int64, comp *repository.Compression) ([]Chunk, error)

	// CalculateHashFunc mocks the CalculateHash method.
	CalculateHashFunc func(ctx context.Context, filePath string, comp *repository.Compression) (string, error)

	// ExploreFunc mocks the Explore method.
	ExploreFunc func(ctx context.Context, sourcePath string) (*Source, error)

	// calls tracks calls to the methods.
	calls struct {
		// CalculateChunks holds details about calls to the CalculateChunks method.
		CalculateChunks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// Size is the size argument value.
			Size int64
			// Comp is the comp argument value.
			Comp *repository.Compression
		}
		// CalculateHash holds details about calls to the CalculateHash method.
		CalculateHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// Comp is the comp argument value.
			Comp *repository.Compression
		}
		// Explore holds details about calls to the Explore method.
		Explore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SourcePath is the sourcePath argument value.
			SourcePath string
		}
	}
	lockCalculateChunks sync.RWMutex
	lockCalculateHash   sync.RWMutex
	lockExplore         sync.RWMutex
}

// CalculateChunks calls CalculateChunksFunc.
func (mock *SourceRepositoryMock) CalculateChunks(ctx context.Context, filePath string, size int64, comp *repository.Compression) ([]Chunk, error) {
	if mock.CalculateChunksFunc == nil {
		panic("SourceRepositoryMock.CalculateChunksFunc: method is nil but SourceRepository.CalculateChunks was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
		Size     int64
		Comp     *repository.Compression
	}{
		Ctx:      ctx,
		FilePath: filePath,
		Size:     size,
		Comp:     comp,
	}
	mock.lockCalculateChunks.Lock()
	mock.calls.CalculateChunks = append(mock.calls.CalculateChunks, callInfo)
	mock.lockCalculateChunks.Unlock()
	return mock.CalculateChunksFunc(ctx, filePath, size, comp)
}

// CalculateChunksCalls gets all the calls that were made to CalculateChunks.
// Check the length with:
//
//	len(mockedSourceRepository.CalculateChunksCalls())
func (mock *SourceRepositoryMock) CalculateChunksCalls() []struct {
	Ctx      context.Context
	FilePath string
	Size     int64
	Comp     *repository.Compression
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
		Size     int64
		Comp     *repository.Compression
	}
	mock.lockCalculateChunks.RLock()
	calls = mock.calls.CalculateChunks
	mock.lockCalculateChunks.RUnlock()
	return calls
}

// CalculateHash calls CalculateHashFunc.
func (mock *SourceRepositoryMock) CalculateHash(ctx context.Context, filePath string, comp *repository.Compression) (string, error) {
	if mock.CalculateHashFunc == nil {
		panic("SourceRepositoryMock.CalculateHashFunc: method is nil but SourceRepository.CalculateHash was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
		Comp     *repository.Compression
	}{
		Ctx:      ctx,
		FilePath: filePath,
		Comp:     comp,
	}
	mock.lockCalculateHash.Lock()
	mock.calls.CalculateHash = append(mock.calls.CalculateHash, callInfo)
	mock.lockCalculateHash.Unlock()
	return mock.CalculateHashFunc(ctx, filePath, comp)
}

// CalculateHashCalls gets all the calls that were made to CalculateHash.
// Check the length with:
//
//	len(mockedSourceRepository.CalculateHashCalls())
func (mock *SourceRepositoryMock) CalculateHashCalls() []struct {
	Ctx      context.Context
	FilePath string
	Comp     *repository.Compression
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
		Comp     *repository.Compression
	}
	mock.lockCalculateHash.RLock()
	calls = mock.calls.CalculateHash
	mock.lockCalculateHash.RUnlock()
	return calls
}

// Explore calls ExploreFunc.
func (mock *SourceRepositoryMock) Explore(ctx context.Context, sourcePath string) (*Source, error) {
	if mock.ExploreFunc == nil {
		panic("SourceRepositoryMock.ExploreFunc: method is nil but SourceRepository.Explore was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		SourcePath string
	}{
		Ctx:        ctx,
		SourcePath: sourcePath,
	}
	mock.lockExplore.Lock()
	mock.calls.Explore = append(mock.calls.Explore, callInfo)
	mock.lockExplore.Unlock()
	return mock.ExploreFunc(ctx, sourcePath)
}

// ExploreCalls gets all the calls that were made to Explore.
// Check the length with:
//
//	len(mockedSourceRepository.ExploreCalls())
func (mock *SourceRepositoryMock) ExploreCalls() []struct {
	Ctx        context.Context
	SourcePath string
} {
	var calls []struct {
		Ctx        context.Context
		SourcePath string
	}
	mock.lockExplore.RLock()
	calls = mock.calls.Explore
	mock.lockExplore.RUnlock()
	return calls
}

// Ensure, that ManifestRepositoryMock does implement ManifestRepository.
// If this is not the case, regenerate this file with moq.
var _ ManifestRepository = &ManifestRepositoryMock{}

// ManifestRepositoryMock is a mock implementation of ManifestRepository.
//
//	func TestSomethingThatUsesManifestRepository(t *testing.T) {
//
//		// make and configure a mocked ManifestRepository
//		mockedManifestRepository := &ManifestRepositoryMock{
//			GetFunc: func(ctx context.Context, snapshotID string) (*Manifest, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context) ([]Manifest, error) {
//				panic("mock out the List method")
//			},
//			SaveFunc: func(ctx context.Context, m *Manifest) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedManifestRepository in code that requires ManifestRepository
//		// and then make assertions.
//
//	}
type ManifestRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, snapshotID string) (*Manifest, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]Manifest, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, m *Manifest) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SnapshotID is the snapshotID argument value.
			SnapshotID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// M is the m argument value.
			M *Manifest
		}
	}
	lockGet  sync.RWMutex
	lockList sync.RWMutex
	lockSave sync.RWMutex
}

// Get calls GetFunc.
func (mock *ManifestRepositoryMock) Get(ctx context.Context, snapshotID string) (*Manifest, error) {
	if mock.GetFunc == nil {
		panic("ManifestRepositoryMock.GetFunc: method is nil but ManifestRepository.Get was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		SnapshotID string
	}{
		Ctx:        ctx,
		SnapshotID: snapshotID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, snapshotID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedManifestRepository.GetCalls())
func (mock *ManifestRepositoryMock) GetCalls() []struct {
	Ctx        context.Context
	SnapshotID string
} {
	var calls []struct {
		Ctx        context.Context
		SnapshotID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ManifestRepositoryMock) List(ctx context.Context) ([]Manifest, error) {
	if mock.ListFunc == nil {
		panic("ManifestRepositoryMock.ListFunc: method is nil but ManifestRepository.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedManifestRepository.ListCalls())
func (mock *ManifestRepositoryMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *ManifestRepositoryMock) Save(ctx context.Context, m *Manifest) error {
	if mock.SaveFunc == nil {
		panic("ManifestRepositoryMock.SaveFunc: method is nil but ManifestRepository.Save was just called")
	}
	callInfo := struct {
		Ctx context.Context
		M   *Manifest
	}{
		Ctx: ctx,
		M:   m,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, m)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedManifestRepository.SaveCalls())
func (mock *ManifestRepositoryMock) SaveCalls() []struct {
	Ctx context.Context
	M   *Manifest
} {
	var calls []struct {
		Ctx context.Context
		M   *Manifest
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that ObjectRepositoryMock does implement ObjectRepository.
// If this is not the case, regenerate this file with moq.
var _ ObjectRepository = &ObjectRepositoryMock{}

// ObjectRepositoryMock is a mock implementation of ObjectRepository.
//
//	func TestSomethingThatUsesObjectRepository(t *testing.T) {
//
//		// make and configure a mocked ObjectRepository
//		mockedObjectRepository := &ObjectRepositoryMock{
//			AlreadyExistsFunc: func(ctx context.Context, hash string) (bool, error) {
//				panic("mock out the AlreadyExists method")
//			},
//			ReadObjectFunc: func(ctx context.Context, hash string) (io.ReadCloser, error) {
//				panic("mock out the ReadObject method")
//			},
//			RestoreObjectFunc: func(ctx context.Context, comp *repository.Compression, obj *File) error {
//				panic("mock out the RestoreObject method")
//			},
//			SaveFunc: func(ctx context.Context, filePath string, hash string, comp *repository.Compression) error {
//				panic("mock out the Save method")
//			},
//			SaveChunkFunc: func(ctx context.Context, filePath string, hash string, offset int64, size int64, comp *repository.Compression) error {
//				panic("mock out the SaveChunk method")
//			},
//		}
//
//		// use mockedObjectRepository in code that requires ObjectRepository
//		// and then make assertions.
//
//	}
type ObjectRepositoryMock struct {
	// AlreadyExistsFunc mocks the AlreadyExists method.
	AlreadyExistsFunc func(ctx context.Context, hash string) (bool, error)

	// ReadObjectFunc mocks the ReadObject method.
	ReadObjectFunc func(ctx context.Context, hash string) (io.ReadCloser, error)

	// RestoreObjectFunc mocks the RestoreObject method.
	RestoreObjectFunc func(ctx context.Context, comp *repository.Compression, obj *File) error

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, filePath string, hash string, comp *repository.Compression) error

	// SaveChunkFunc mocks the SaveChunk method.
	SaveChunkFunc func(ctx context.Context, filePath string, hash string, offset int64, size int64, comp *repository.Compression) error

	// calls tracks calls to the methods.
	calls struct {
		// AlreadyExists holds details about calls to the AlreadyExists method.
		AlreadyExists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
		// ReadObject holds details about calls to the ReadObject method.
		ReadObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
		// RestoreObject holds details about calls to the RestoreObject method.
		RestoreObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Comp is the comp argument value.
			Comp *repository.Compression
			// Obj is the obj argument value.
			Obj *File
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// Hash is the hash argument value.
			Hash string
			// Comp is the comp argument value.
			Comp *repository.Compression
		}
		// SaveChunk holds details about calls to the SaveChunk method.
		SaveChunk []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilePath is the filePath argument value.
			FilePath string
			// Hash is the hash argument value.
			Hash string
			// Offset is the offset argument value.
			Offset int64
			// Size is the size argument value.
			Size int64
			// Comp is the comp argument value.
			Comp *repository.Compression
		}
	}
	lockAlreadyExists sync.RWMutex
	lockReadObject    sync.RWMutex
	lockRestoreObject sync.RWMutex
	lockSave          sync.RWMutex
	lockSaveChunk     sync.RWMutex
}

// AlreadyExists calls AlreadyExistsFunc.
func (mock *ObjectRepositoryMock) AlreadyExists(ctx context.Context, hash string) (bool, error) {
	if mock.AlreadyExistsFunc == nil {
		panic("ObjectRepositoryMock.AlreadyExistsFunc: method is nil but ObjectRepository.AlreadyExists was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockAlreadyExists.Lock()
	mock.calls.AlreadyExists = append(mock.calls.AlreadyExists, callInfo)
	mock.lockAlreadyExists.Unlock()
	return mock.AlreadyExistsFunc(ctx, hash)
}

// AlreadyExistsCalls gets all the calls that were made to AlreadyExists.
// Check the length with:
//
//	len(mockedObjectRepository.AlreadyExistsCalls())
func (mock *ObjectRepositoryMock) AlreadyExistsCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockAlreadyExists.RLock()
	calls = mock.calls.AlreadyExists
	mock.lockAlreadyExists.RUnlock()
	return calls
}

// ReadObject calls ReadObjectFunc.
func (mock *ObjectRepositoryMock) ReadObject(ctx context.Context, hash string) (io.ReadCloser, error) {
	if mock.ReadObjectFunc == nil {
		panic("ObjectRepositoryMock.ReadObjectFunc: method is nil but ObjectRepository.ReadObject was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockReadObject.Lock()
	mock.calls.ReadObject = append(mock.calls.ReadObject, callInfo)
	mock.lockReadObject.Unlock()
	return mock.ReadObjectFunc(ctx, hash)
}

// ReadObjectCalls gets all the calls that were made to ReadObject.
// Check the length with:
//
//	len(mockedObjectRepository.ReadObjectCalls())
func (mock *ObjectRepositoryMock) ReadObjectCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockReadObject.RLock()
	calls = mock.calls.ReadObject
	mock.lockReadObject.RUnlock()
	return calls
}

// RestoreObject calls RestoreObjectFunc.
func (mock *ObjectRepositoryMock) RestoreObject(ctx context.Context, comp *repository.Compression, obj *File) error {
	if mock.RestoreObjectFunc == nil {
		panic("ObjectRepositoryMock.RestoreObjectFunc: method is nil but ObjectRepository.RestoreObject was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Comp *repository.Compression
		Obj  *File
	}{
		Ctx:  ctx,
		Comp: comp,
		Obj:  obj,
	}
	mock.lockRestoreObject.Lock()
	mock.calls.RestoreObject = append(mock.calls.RestoreObject, callInfo)
	mock.lockRestoreObject.Unlock()
	return mock.RestoreObjectFunc(ctx, comp, obj)
}

// RestoreObjectCalls gets all the calls that were made to RestoreObject.
// Check the length with:
//
//	len(mockedObjectRepository.RestoreObjectCalls())
func (mock *ObjectRepositoryMock) RestoreObjectCalls() []struct {
	Ctx  context.Context
	Comp *repository.Compression
	Obj  *File
} {
	var calls []struct {
		Ctx  context.Context
		Comp *repository.Compression
		Obj  *File
	}
	mock.lockRestoreObject.RLock()
	calls = mock.calls.RestoreObject
	mock.lockRestoreObject.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *ObjectRepositoryMock) Save(ctx context.Context, filePath string, hash string, comp *repository.Compression) error {
	if mock.SaveFunc == nil {
		panic("ObjectRepositoryMock.SaveFunc: method is nil but ObjectRepository.Save was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
		Hash     string
		Comp     *repository.Compression
	}{
		Ctx:      ctx,
		FilePath: filePath,
		Hash:     hash,
		Comp:     comp,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, filePath, hash, comp)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedObjectRepository.SaveCalls())
func (mock *ObjectRepositoryMock) SaveCalls() []struct {
	Ctx      context.Context
	FilePath string
	Hash     string
	Comp     *repository.Compression
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
		Hash     string
		Comp     *repository.Compression
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// SaveChunk calls SaveChunkFunc.
func (mock *ObjectRepositoryMock) SaveChunk(ctx context.Context, filePath string, hash string, offset int64, size int64, comp *repository.Compression) error {
	if mock.SaveChunkFunc == nil {
		panic("ObjectRepositoryMock.SaveChunkFunc: method is nil but ObjectRepository.SaveChunk was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilePath string
		Hash     string
		Offset   int64
		Size     int64
		Comp     *repository.Compression
	}{
		Ctx:      ctx,
		FilePath: filePath,
		Hash:     hash,
		Offset:   offset,
		Size:     size,
		Comp:     comp,
	}
	mock.lockSaveChunk.Lock()
	mock.calls.SaveChunk = append(mock.calls.SaveChunk, callInfo)
	mock.lockSaveChunk.Unlock()
	return mock.SaveChunkFunc(ctx, filePath, hash, offset, size, comp)
}

// SaveChunkCalls gets all the calls that were made to SaveChunk.
// Check the length with:
//
//	len(mockedObjectRepository.SaveChunkCalls())
func (mock *ObjectRepositoryMock) SaveChunkCalls() []struct {
	Ctx      context.Context
	FilePath string
	Hash     string
	Offset   int64
	Size     int64
	Comp     *repository.Compression
} {
	var calls []struct {
		Ctx      context.Context
		FilePath string
		Hash     string
		Offset   int64
		Size     int64
		Comp     *repository.Compression
	}
	mock.lockSaveChunk.RLock()
	calls = mock.calls.SaveChunk
	mock.lockSaveChunk.RUnlock()
	return calls
}
